image: Visual Studio 2013

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

before_build:
  - mkdir build
  - cd build
  - cmake .. -A %PLATFORM%

build:
  project: build\task01.sln
  parallel: true
  verbosity: normal

test_script:
  - ctest -V -C %CONFIGURATION%
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test_detail.xml))
